#!/usr/bin/env perl
use strict;
use warnings;

# 以下の問題をPerlの四則演算を使って解いてください。
# 変数 `$pizza` を使って解いて表示してください
# １０個のピザを５人で分けた時の、一人当たりの個数

my $pizza = 10;
print $pizza / 5 . "\n";


# １０個のピザを３人で分けた時の、余りの数
print $pizza % 3 . "\n";